environments:
  all:
    pipelines:
      - dotnet-build
      - dotnet-package
      - dotnet-FT
      - python-build
      - python-package
      - python-FT 
      - python-lsp-tests
      - python-release
      - gauge-proto
      - CSharp-Lib
      - CSharp-Core
      - Csharp-FT-New
      - dotnet-LSP
      - Gauge-Build
      - Gauge-Deploy
      - Gauge-Deploy-Brew
      - Gauge-Deploy-Choco
      - Gauge-Deploy-Deb
      - Gauge-Deploy-RPM
      - Gauge-Deploy-NPM
      - Ruby-FT
      - Ruby-LSP-Tests
      - JS-FT
      - JS-LSP-Tests
      - Taiko
      - Java-Build-New
      - Java-FT
      - Java-Deploy
      - VSCode-Build
      - VSCode-Tests