pipelines:
  check-all-readme-files:
    group: Misc
    materials:
      gauge_docs:
        pipeline: docs.gauge.org
        stage: deploy
      gauge_website:
        pipeline: gauge.org
        stage: deploy-live
    timer:
      spec: "0 0 12 ? * SUN *"
    stages:
      - getgauge_repo:
          clean_workspace: true
          jobs:
            check:
              resources:
                - darwin
                - UT
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                      - -g
                      - --prefix
                      - /tmp
                      - markdown-link-check
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge/repos?access_token=$GITHUB_ACCESS_TOKEN | jq -r '.[].clone_url' | xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge-examples/repos?access_token=$GITHUB_ACCESS_TOKEN | jq -r '.[].clone_url' | xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge-contrib/repos?access_token=$GITHUB_ACCESS_TOKEN | jq -r '.[].clone_url' | xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - find . -iname \*.md -maxdepth 2 -mindepth 2 | xargs -L1 /tmp/bin/markdown-link-check
                - exec:
                    run_if: any
                    command: touch
                    arguments:
                    - /vagrant/rollback.txt
