pipelines:
  Taiko:
    group: Gauge-JS
    materials:
      taiko:
        git: https://github.com/getgauge/taiko.git
    stages:
      - test:
          jobs:
            test:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
      - specs:
          jobs:
            linux-specs:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: git
                    arguments:
                      - clone
                      - https://github.com/getgauge-examples/js-taiko
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - npm uninstall -g taiko
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - install
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -SsL https://downloads.getgauge.io/stable | sh -s -- --location=$(pwd)
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - update
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gauge install && ./gauge run -p -v specs --tags=\!knownIssue
            windows-specs:
              resources:
               - windows
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "git clone https://github.com/getgauge-examples/js_puppeteer"
               - exec:
                   working_directory: js_puppeteer
                   command: cmd
                   arguments:
                    - /c
                    - "curl -SsL https://downloads.getgauge.io/stable | sh -s -- --location=$(pwd)"
                    - uninstall
                    - dotnet
                - exec:
                    working_directory: js_puppeteer
                    command: cmd
                    arguments:
                      - /c
                      - "npm install"
                - exec:
                    working_directory: js_puppeteer
                    command: cmd
                    arguments:
                      - /c
                      - "./gauge install && ./gauge run -p -v specs --tags=\!knownIssue"
      - publish:
          approval: manual
          jobs:
            publish:
              elastic_profile_id: ubuntu-node
              secure_variables:
                NPM_TOKEN: efUvjzmZzPgw+zldFDyT8faQLZbL4k22+a4wkQe67TUZp9pXU4XCAA==
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc && npm publish
