pipelines:
  Taiko:
    group: Gauge-JS
    materials:
      taiko:
        git: https://github.com/getgauge/taiko.git
      gauge:
        pipeline: Gauge-Package
        stage: windows
    stages:
      - test:
          jobs:
            test:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
      - specs:
          jobs:
            linux-specs:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: git
                    arguments:
                      - clone
                      - https://github.com/getgauge-examples/js-taiko
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - npm uninstall -g taiko
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - install
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -SsL https://downloads.getgauge.io/stable | sh -s -- --location=$(pwd)
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - update
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gauge install && ./gauge run -p -v specs --tags=\!knownIssue
            osx-specs:
              resources:
                - darwin
                - FT
              tasks:
                - exec:
                    command: git
                    arguments:
                      - clone
                      - https://github.com/getgauge-examples/js-taiko
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - npm uninstall -g taiko
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - install
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -SsL https://downloads.getgauge.io/stable | sh -s -- --location=$(pwd)
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - update
                - exec:
                    working_directory: js-taiko
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gauge install && ./gauge run -v specs --tags=\!knownIssue
            windows-specs:
              elastic_profile_id: windows-all
              environment_variables:
                GAUGE_ROOT: C:\gauge_root
              tasks:
                - exec:
                    command: git
                    arguments:
                      - clone
                      - https://github.com/getgauge-examples/js-taiko
                - exec:
                    working_directory: js-taiko
                    command: cmd
                    arguments:
                      - /c
                      - npm uninstall -g taiko
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - install
                - fetch:
                    pipeline: Gauge-Package
                    stage: windows
                    job: sign
                    is_file: yes
                    source: test_installers/gauge-windows.x86_64.zip
                - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "unzip -o gauge-windows.x86_64.zip -d %GAUGE_ROOT%"
                - exec:
                    working_directory: js-taiko
                    command: npm
                    arguments:
                      - update
                - exec:
                    working_directory: js-taiko
                    command: cmd
                    arguments:
                      - /c
                      - "%GAUGE_ROOT%/gauge"
                      - install
                - exec:
                    working_directory: js-taiko
                    command: cmd
                    arguments:
                      - /c                      
                      - "%GAUGE_ROOT%/gauge run specs --tags=!knownIssue"
      - publish:
          approval: manual
          jobs:
            publish:
              elastic_profile_id: ubuntu-node
              secure_variables:
                NPM_TOKEN: efUvjzmZzPgw+zldFDyT8faQLZbL4k22+a4wkQe67TUZp9pXU4XCAA==
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc && npm publish