pipelines:
  gauge.org:
    group: Websites
    materials:
      website:
        git: https://github.com/getgauge/gauge.org.git
    stages:
      - build:
          jobs:
            build:
              environment_variables:
                DOCS_VERSION: master
                BASE_URL: https://preview.gauge.org
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: rbenv
                    arguments:
                      - local
                      - 2.4.0
                - exec:
                    command: bundle
                    arguments:
                      - install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/nodejs010/root/usr/lib64/ bundle exec middleman build --verbose)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - echo $GO_REVISION_WEBSITE > build/version.txt
              artifacts:
               - build:
                   source: build/*
                   destination: deploy
      - deploy-preview:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: MsgNaRPRZFDlyccRoC5exAK9DfmTzzaT
                aws_secret_access_key: Ya/3nrdaiGyESQtV0VzXplN14zffxSFbvKY5YxGOmNM4ccsN7Omu0FMx7sH6bF8y
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3
                      - rm
                      - s3://preview.gauge.org
                      - --recursive
                - fetch:
                    stage: build
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3
                      - sync
                      - .
                      - s3://preview.gauge.org
                      - --cache-control
                      - max-age=604800,s-maxage=1800
      - build-live:
          approval: manual
          jobs:
            build:
              environment_variables:
                DOCS_VERSION: latest
                BASE_URL: https://gauge.org
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: rbenv
                    arguments:
                      - local
                      - 2.4.0
                - exec:
                    command: bundle
                    arguments:
                      - install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/nodejs010/root/usr/lib64/ bundle exec middleman build --verbose)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - echo $GO_REVISION_WEBSITE > build/version.txt
              artifacts:
               - build:
                   source: build/*
                   destination: deploy
      - deploy-live:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: MsgNaRPRZFDlyccRoC5exAK9DfmTzzaT
                aws_secret_access_key: Ya/3nrdaiGyESQtV0VzXplN14zffxSFbvKY5YxGOmNM4ccsN7Omu0FMx7sH6bF8y
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3
                      - rm
                      - s3://gauge.org
                      - --recursive
                - fetch:
                    stage: build-live
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3
                      - sync
                      - .
                      - s3://gauge.org
                      - --cache-control
                      - max-age=604800,s-maxage=1800
  docs.gauge.org:
    group: Websites
    label_template: ${COUNT}
    materials:
      website:
        git: https://github.com/getgauge/docs.getgauge.io.git
      gauge:
        pipeline: gauge-deploy
        stage: docs
    environment_variables:
      LC_ALL: en_US.utf-8
      LANG: en_US.utf-8
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command:  git
                    arguments:
                      - version
                - exec:
                    command: virtualenv
                    arguments:
                      - docs
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - source ./docs/bin/activate && pip install -r requirements.txt && make zip && deactivate
              artifacts:
               - build:
                    source: _build/html/*
                    destination: deploy
      - deploy:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: AES:dH5bwy34WSzQmUChLz5Sqw==:LCLuya+iy1vIuW5x1dBq1vKvHLfVMQncV6ABMdc+rFI=
                aws_secret_access_key: AES:+PTrCMdaQCEAdhFM5z6EjA==:qGiUjD9Y6B5mtzPocpCt5DyHF/JvVQVKu0i1iD0su4CX6Nbr5GQq/GDU4JemreC9
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://docs.gauge.org/latest --recursive
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://docs.gauge.org/master --recursive
                - fetch:
                    stage: build
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3 sync . s3://docs.getgauge.io --cache-control max-age=604800,s-maxage=1800
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3 sync . s3://docs.gauge.org --cache-control max-age=604800,s-maxage=1800